### ISSUE TITLE
SVD, different than numpy

### ISSUE THREAD

**Issue by emrahgunduz** [AlexanderTar/LASwift#15]
Hi,

I'm trying to convert a layer calculation from Python to Swift using your library. But I think there is a calculation problem in your solution for singular value decomposition.

This is an example matrix I'm getting on first calculation loop. Both python and Swift response with the same matrix:

```[
[
 [ 6.5  -0.5   0.    0.5  -6.5 ], 
 [-0.5   7.25  6.25  5.25  0.5 ], 
 [ 0.    6.25  6.25  6.25  0.  ], 
 [ 0.5   5.25  6.25  7.25 -0.5 ], 
 [-6.5   0.5   0.   -0.5   6.5 ]
]
```

With numpy I'm calculating svd as:

```python
u, d, v_t = np.linalg.svd( cov_matrix, full_matrices=True )
```

For LASwift library I'm simply calling svd function as there are no arguments for the method. Numpy returns the response as `u, d, v_t`, but LASwift, even though the namings are the same returns a response as `v, d, u`. 

Most important is, the response starts to differ after a few rows and/or colums.

#### Numpy U vs LASwift U
Last two columns are different.
```
 0.00000, -0.70425,  0.06350,  0.24434,  0.66355
-0.57735,  0.06350,  0.70425, -0.38310,  0.14107
-0.57735, -0.00000,  0.00000,  0.76620, -0.28214
-0.57735, -0.06350, -0.70425, -0.38310,  0.14107
-0.00000,  0.70425, -0.06350,  0.24434,  0.66355
```

```
 0.00000, -0.70425,  0.06350,  0.44473, -0.54974
-0.57735,  0.06350,  0.70425,  0.31739,  0.25677
-0.57735, -0.00000, -0.00000, -0.63478, -0.51353
-0.57735, -0.06350, -0.70425,  0.31739,  0.25677
 0.00000,  0.70425, -0.06350,  0.44473, -0.54974
```

#### Numpy D vs LASwift D
Same, but needs a collapse (not important).
```
18.75000, 13.09017, 1.90983, 0.00000, 0.00000

18.75000,  0.00000, 0.00000, 0.00000, 0.00000
 0.00000, 13.09017, 0.00000, 0.00000, 0.00000
 0.00000,  0.00000, 1.90983, 0.00000, 0.00000
 0.00000,  0.00000, 0.00000, 0.00000, 0.00000
 0.00000,  0.00000, 0.00000, 0.00000, 0.00000
```

#### Numpy Vt vs LASwift Vt
Last two rows are different.
```
 0.00000, -0.57735, -0.57735, -0.57735,  0.00000
-0.70425,  0.06350, -0.00000, -0.06350,  0.70425
 0.06350,  0.70425,  0.00000, -0.70425, -0.06350
 0.54102, -0.26286,  0.52573, -0.26286,  0.54102
 0.45529,  0.31236, -0.62472,  0.31236,  0.45529
 
 0.00000, -0.57735, -0.57735, -0.57735, -0.00000
-0.70425,  0.06350, -0.00000, -0.06350,  0.70425
 0.06350,  0.70425,  0.00000, -0.70425, -0.06350
-0.13761, -0.40044,  0.80089, -0.40044, -0.13761
 0.69359, -0.07945,  0.15889, -0.07945,  0.69359
```

Why the response changes and is there a way to solve this?

**Comment by ianruh** [comment]
Hi @emrahgunduz, as for your first question about the naming, I'm not sure I understand.

For your second question, both are actually correct (and if we do the svd in MatLab, we get a third different, but equally correct, answer). The initial matrix you gave is singular, with order three. So, we only get three non-zero singular values (18.75000, 13.09017, 1.90983). The singular vectors associated with those singular values (both the left and the right) are uniquely determined (assuming everything is real valued). However, because the last two singular values are zero, the last two singular vectors are not unique. The only requirement of the last two singular vectors is that they are orthogonal to the other singular vectors.

You can verify this by checking that u*d*v' equals your initial matrix for both the swift and numpy implementations of the svd.

[Here](https://math.stackexchange.com/questions/644327/how-unique-are-u-and-v-in-the-singular-value-decomposition) is a more detailed (and probably more mathematically correct) explanation on Stack Exchange.

**Comment by emrahgunduz** [comment]
The Stack Exchange link pretty much answers my question.
Thanks for the explanation.
👍
