### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by machineko** [AlexanderTar/LASwift#23]
Are you planning on adding Linux support or it's just focused on pure macOS ecosystem?

**Comment by AlexanderTar** [comment]
This library is heavily based on Apple's Accelerate framework. While some parts of it are available on Linux platforms as open-source libraries, a big part of it is proprietary and requires significant changes in order to mimic same functionality under Linux.

I'm not planning on investing effort into supporting Linux at the moment, however I would be open to contributions if this becomes important.

Hope you understand.
