### ISSUE TITLE
Multiplication of matrixes

### ISSUE THREAD

**Issue by Arman1997** [AlexanderTar/LASwift#5]
I tried to multiply two non square matrices and get the error cause of this

<img width="564" alt="screen shot 2017-09-19 at 2 21 07 am" src="https://user-images.githubusercontent.com/20797432/30567505-c3efd2da-9ce1-11e7-86ba-3fc1ae158610.png">

i think this precondition is wrong the true precondition must be
`precondition(A.cols == B.rows)
`

**Comment by AlexanderTar** [comment]
This is probably because you tried to use element-wise multiplication for matrix multiplication. If you want to multiply two matrices, you should use `mtimes` function or `*` operator. `times` function does element-wise multiplication, in this case dimensions of matrices should be the same and the result will have same dimensions too. Please, let me know if this worked or if you have any other issues.

**Comment by Arman1997** [comment]
everything is working, thanks
